In [41]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

data = pd.read_csv("../datasets/correlational.csv")

In [42]:
df = data
non_categorical_col = df['vehicleregistrationnumber']
label = df["label"]
df.drop("label", axis=1, inplace=True)
df.drop("vehicleregistrationnumber", axis=1, inplace=True)
categorical_cols = ['vehicletype', 'vehiclemodel', 'vehicleprimaryuse']

# One-hot encode categorical columns
one_hot_encoded = pd.get_dummies(df, columns=categorical_cols, dtype=float)

# Concatenate one-hot encoded columns with non-categorical columns
encoded_df = pd.concat([one_hot_encoded, non_categorical_col, label], axis=1)
encoded_df.head()

,vehicletype_0,vehicletype_1,vehicletype_2,vehiclemodel_0,vehiclemodel_1,vehiclemodel_2,vehiclemodel_3,vehiclemodel_4,vehiclemodel_5,vehiclemodel_6,...,vehicleprimaryuse_5,vehicleprimaryuse_6,vehicleprimaryuse_7,vehicleprimaryuse_8,vehicleprimaryuse_9,vehicleprimaryuse_10,vehicleprimaryuse_11,vehicleprimaryuse_12,vehicleregistrationnumber,label
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,35
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,35
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1,13
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1,35
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3,35

In [43]:
df = encoded_df
registration_number_index = df.columns.get_loc('vehicleregistrationnumber')

# Normalize the vehicleregistrationnumber column
scaler = MinMaxScaler()
df_normalized = scaler.fit_transform(df[['vehicleregistrationnumber']])
df_normalized = pd.DataFrame(df_normalized, columns=['vehicleregistrationnumber'])

# Drop the original unnormalized column
df.drop('vehicleregistrationnumber', axis=1, inplace=True)

# Insert the normalized column at the original position
df.insert(registration_number_index, 'vehicleregistrationnumber', df_normalized)

In [46]:
df.to_csv("../datasets/final.csv", index=False)